server:
  port: 9876

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: hotel-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  datasource:
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS hoteldb;
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      schema-locations: classpath:schema-h2.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO